services:
  admin:
    container_name: admin
    build: 
      context: .
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000"
    env_file:
      - .env.production
    networks:
      - app-network
    volumes:
      - ./src:/usr/src/app/src
    depends_on:
      - db
  
  db:
    container_name: db
    image: mysql:latest
    restart: always
    ports:
      - "3307:3306"
    env_file:
      - .env.production
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data:

networks:
  app-network:
    driver: bridge
    external: true